### ISSUE TITLE
Tests are flaky on travis

### ISSUE THREAD

**Issue by nomiddlename** [log4js-node/streamroller#14]
Tests seem to fail intermittently on travis - I suspect due to timing issues with file operations (we're probably not doing async i/o properly somewhere).

**Comment by cula** [comment]
Fixed at this [commit](https://github.com/log4js-node/streamroller/commit/767d11e7d4ce2f97f125a2fc8a353164ff101497). 

@nomiddlename  I have a totally recoding in this commit. **Please make a check.**
I do not change test cases to make it adapt all features I found on the docs.

**Comment by nomiddlename** [comment]
Looks good @cula - thanks for doing this. [proxyquire](https://github.com/thlorenz/proxyquire) looks interesting, I might replace sandboxed-module with it for some of the other projects. I've published this to NPM as well.
