### ISSUE TITLE
not support node v10

### ISSUE THREAD

**Issue by ben-lau** [log4js-node/streamroller#145]
Your dependencies of fs-extra@10.0.0 is no longer support node v10: [changelog](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#1000--2021-05-03)

So maybe you should change the engines version from node>=8 to node>=12.

Also change log4js after version 6.3.0, cause it make my project error.

Thank you.

**Comment by ben-lau** [comment]
your dependencies of fs-extra@10.0.0 is no longer support node v10: [changelog](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#1000--2021-05-03)

so maybe you should change the engines version from node>=8 to node>=12.

also change log4js after version 6.3.0, cause it make my project error.

thank you.

**Comment by lamweili** [comment]
We are using GitHub actions to cover Node 12, 14, 16 for both [`log4js`](https://github.com/log4js-node/log4js-node/blob/6acc345b598525a47703a9d0072996453c8c7290/.github/workflows/node.js.yml#L19) and [`streamroller`](https://github.com/log4js-node/streamroller/blob/54bca6ab3d6065184fee1bbbbddd411ba537b1d4/.github/workflows/node.js.yml#L19).

https://github.com/log4js-node/streamroller/blob/54bca6ab3d6065184fee1bbbbddd411ba537b1d4/.github/workflows/node.js.yml#L19

**Comment by ben-lau** [comment]
But the dependence fs-extra is over version 10, which is not support node 10.

In strearoller and log4js pkg shows that supports node version over 8

https://github.com/log4js-node/streamroller/blob/master/package.json#L50

I think it should change to node>=12.0.0 or use lower version of fs-extra

**Comment by lamweili** [comment]
Ah, I get what you mean.

May I know what is the working version of `NodeJS`, `log4js` and `streamroller` that you were using?

**Comment by ben-lau** [comment]
npmPackages:
    @types/cross-spawn: ^6.0.2 => 6.0.2 
    @types/fs-extra: ^9.0.13 => 9.0.13 
    @types/inquirer: ^7.3.1 => 7.3.3 
    @types/node: ^14.14.13 => 14.18.21 
    @typescript-eslint/eslint-plugin: ^4.9.1 => 4.33.0 
    @typescript-eslint/parser: ^4.9.1 => 4.33.0 
    chalk: ^4.1.0 => 4.1.2 
    commander: ^6.2.1 => 6.2.1 
    conventional-changelog-cli: ^2.2.2 => 2.2.2 
    cross-spawn: ^7.0.3 => 7.0.3 
    eslint: ^7.15.0 => 7.32.0 
    fs-extra: ^9.1.0 => 9.1.0 
    husky: ^4.3.0 => 4.3.8 
    inquirer: ^7.3.3 => 7.3.3 
    log4js: ^6.3.0 => 6.5.2 
    minimist: ^1.2.5 => 1.2.6 
    open: ^7.3.0 => 7.4.2 
    ora: ^5.1.0 => 5.4.1 
    rimraf: ^3.0.2 => 3.0.2 
    rollup: ^2.34.2 => 2.75.7 
    rollup-plugin-typescript2: ^0.30.0 => 0.30.0 
    rollup-plugin-uglify: ^6.0.4 => 6.0.4 
    serialize-javascript: >=3.1.0 => 6.0.0 
    standard-version: ^9.3.2 => 9.5.0 
    tslib: ^2.3.0 => 2.4.0 
    typescript: ^4.1.3 => 4.7.4 


My project has to supports node 10, so I have to make sure all my dependencies is suitable.

**Comment by ben-lau** [comment]
Oh, cause I use ^6.3.0 log4js, when the log4js version is 6.4.0 my project broken

**Comment by lamweili** [comment]
> Oh, cause I use ^6.3.0 log4js, when the log4js version is 6.4.0 my project broken

What is the NodeJS version when it broke? Node 8?

And now you have upgraded to Node 10?

**Comment by ben-lau** [comment]
node 10.24.1

**Comment by ben-lau** [comment]
hello? Is there any plan to fix the specify version of node ?

**Comment by lamweili** [comment]
Hi, apologies for the delayed replies as we are voluntarily helping in our free time.
No doubt this has to be updated. The question is when; how urgent and critical is this issue.

- Will having `node>=12` resolve your issue?
From what I see, you are stuck in Node.js v10 so I don't think that will help.

- Are you going to upgrade to Node.js v12 and above?
If so, you don't have to wait for the new release.

---

In any case, you should upgrade as Node.js v10 is EOL.
That should resolve your issue immediately.  

Node.js | EOL Date | Status (as of 8 Jul 2022)
-|-|-
16 | 11 Sep 2023 | 14 months remaining
14 | 30 Apr 2023 | 9 months remaining
12 | 30 Apr 2022 | EOL
10 | 30 Apr 2021 | EOL

**Comment by ben-lau** [comment]
Sure, I knew I should upgrade, also I have solved this problem. However, it's still an issue of the specify version of node, and I hope there's a plan to fix it. Thank you so much.

**Comment by lamweili** [comment]
It is in the works. 

I understand that there was no announcement for the removal of support for Node.js 8.
The last removal of support was for Node.js 6 (in [`log4js@^5.0.0`](https://github.com/log4js-node/log4js-node/blob/master/CHANGELOG.md#500) and [`streamroller@^2.0.0`](https://github.com/log4js-node/streamroller/blob/master/CHANGELOG.md#200))

To restore the semantic versioning rules:

- [ ] Roll back **_certain changes_** to restore Node.js 8 compatibility in `log4js@^6.0.0` and `streamroller@^3.0.0`
- [ ] Announce the removal of support for Node.js 8 (and maybe some more) to be in the next major version
- [ ] Move the **_certain changes_** to `log4js@^7.0.0` and `streamroller@^4.0.0` instead

**Comment by lamweili** [comment]
To update, PR #147 has made the current `streamroller` codes backwards compatible.
Next would be to resolve dependencies' requirements.

**Comment by lamweili** [comment]
@ben-lau, based on PR #148, compatibility has been restored for Node.js 8 which includes downgrading of `fs-extra`.
Added Node.js 8 CI tests and the results passed: https://github.com/log4js-node/streamroller/actions/runs/2720339487

Released as `streamroller@3.1.2`.

**Comment by ben-lau** [comment]
@lamweili Thank you so much for all your done, **this is a rigorous change**. Our project also will upgrade node version, to embrace technological change
