### ISSUE TITLE
Question: Missing Documentation of "Flags"

### ISSUE THREAD

**Issue by emouawad** [log4js-node/streamroller#16]
What are the different variations of "flags" in "options", I understand by default it's 'a' but what other variations & how they differ?

I need to make the DateRollingFile flush to the file on each write - and make the file always accessible & updated (Opened) in a text editor

**Comment by nomiddlename** [comment]
The 'flags' values are documented here:
https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_open_path_flags_mode_callback

I think maybe 'rs+' would be the value you want? I haven't tried this, by the way.

**Comment by nomiddlename** [comment]
I've updated the Readme with a link to the flags documentation. Thanks for bringing this up.

**Comment by emouawad** [comment]
Thank you, will try it as you suggested.
