### ISSUE TITLE
RollingFileStream will remove every content if old file was created yesterday

### ISSUE THREAD

**Issue by tdzl2003** [log4js-node/streamroller#21]
I created a simple rolling stream:

```
  const { RollingFileStream } = require('streamroller');
  const stream = new RollingFileStream('./data/message.csv', 1 << 20, {
    compress: true,
  });
```

When I restart server next day, all logs was cleared.

These code of streamroller was executed:

```
if(hotFileDate.isBefore(now, 'day')) {
        debug('deleting the existing hot file');
        fs.unlinkSync(path.format(this.fileObject));
      }
```

Even when I don't need date-rolling. ( I think it's also bug for DateRollingFileStream, but I didn't test it)

`streamroller@0.5.2` has no same bug.

**Comment by tdzl2003** [comment]
delete the old hot file makes no sense. If it's before today, it should be rolled, not just deleted.

**Comment by nomiddlename** [comment]
Thanks for raising this issue @tdzl2003, sorry that you lost log files. @cula - would you be able to take a look into this one?

**Comment by cula** [comment]
@nomiddlename ok。Sorry for that。I'll submit a patch within 2 days

**Comment by cula** [comment]
@nomiddlename [fix](https://github.com/log4js-node/streamroller/pull/22)
Fix the above issue and add test cases.
Please make a review.

**Comment by cula** [comment]
@nomiddlename could u please take review of the pull request and publish a patch. thx
