### ISSUE TITLE
'daysToKeep' option doesn't work properly when pattern is '.yyyy-MM-dd-hh'

### ISSUE THREAD

**Issue by wenbin-ding** [log4js-node/streamroller#55]
My log files are set to hourly log rolling, when i set 'daysToKeep' to 3, there's only three file retained instead of 72 files after log rolling.

the packages version: 
log4js@4.5.1
streamroller@1.0.6

my log file configuration:
`{
filename: `${LOG4JS_BASE_DIR}/${filename}`,
type: 'dateFile',
pattern: '.yyyy-MM-dd-hh',
alwaysIncludePattern: true,
daysToKeep: 3
}`

It seems that the daysToKeep used as numToKeep in source code.

**Comment by nomiddlename** [comment]
Yes, sorry - the docs are not very clear. If you are not rolling log files daily, then `daysToKeep` is interpreted as `numToKeep` - so in your case, set it to 72 instead of 3.

**Comment by wenbin-ding** [comment]
Thanks for reply, it helps.
