### ISSUE TITLE
There is an extra separator.

### ISSUE THREAD

**Issue by pikadun** [log4js-node/streamroller#64]
https://github.com/log4js-node/streamroller/blob/e9ba0d85155ba0e8561f219faf084d521708885e/lib/fileNameFormatter.js#L3

I have a dateFile appender like this 
``` js
{
            type: 'dateFile',
            filename: 'log/info/info',
            pattern: '-yyyy-MM-dd.log',
            alwaysIncludePattern: true,
}
```

it should create a file which name like `log/info/info-yyyy-MM-dd.log` but not `log/info/info.-yyyy-MM-dd.log`

**Comment by peteriman** [comment]
From the code, if the `pattern` starts with `.`, the `.` is removed.
https://github.com/log4js-node/streamroller/blob/e9ba0d85155ba0e8561f219faf084d521708885e/lib/DateRollingFileStream.js#L19-L21

Subsequently, `FILENAME_SEP` (or `.`) is added to the front of the resultant `pattern`.
https://github.com/log4js-node/streamroller/blob/e9ba0d85155ba0e8561f219faf084d521708885e/lib/fileNameFormatter.js#L17-L22

I believe this is the issue.

---

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    test1: { 
      type: 'dateFile', 
      filename: 'test1.log', 
      pattern: '.yyyy-MM-dd', 
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
    test2: { 
      type: 'dateFile', 
      filename: 'test2.log', 
      pattern: '-yyyy-MM-dd', 
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
  },
  categories: {
    default: { appenders: [ 'test1', 'test2' ], level: 'debug' }
  }
});
```

Expected: 
`test1.2022-01-07.log` `test2-2022-01-07.log`
Actual: 
`test1.2022-01-07.log` `test2.-2022-01-07.log`

**Comment by peteriman** [comment]
It works now.

```javascript
const log4js = require('log4js');
log4js.configure({
  appenders: {
    test1: { 
      type: 'dateFile', 
      filename: 'test1.log', 
      pattern: 'yyyy-MM-dd', 
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
    test2: { 
      type: 'dateFile', 
      filename: 'test2.log', 
      pattern: 'yyyy-MM-dd',
      fileNameSep: '_',
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
    test3: { 
      type: 'dateFile', 
      filename: 'test3.log', 
      pattern: '.yyyy-MM-dd', 
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
    test4: { 
      type: 'dateFile', 
      filename: 'test4.log', 
      pattern: '-yyyy-MM-dd', 
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
    test5: { 
      type: 'dateFile', 
      filename: 'test5.log', 
      pattern: '.-yyyy-MM-dd', 
      alwaysIncludePattern: true, 
      keepFileExt: true
    },
  },
  categories: {
    default: { appenders: [ 'test1', 'test2', 'test3', 'test4', 'test5' ], level: 'debug' }
  }
});
```


|Pattern|Separator|Expected|Actual|Test
|-|-|-|-|-|
|`yyyy-MM-dd`|.|`test1.2022-01-07.log` | `test1.2022-01-07.log`|✔️|
|`yyyy-MM-dd`|_|`test2_2022-01-07.log` | `test2_2022-01-07.log`|✔️|
|`.yyyy-MM-dd`|. (default)|`test3..2022-01-07.log` | `test3..2022-01-07.log`|✔️|
|`-yyyy-MM-dd`|. (default)|`test4.-2022-01-07.log`| `test4.-2022-01-07.log`|✔️|
|`.-yyyy-MM-dd`|. (default)|`test5..-2022-01-07.log`| `test5..-2022-01-07.log`|✔️|
